#!/bin/bash -eu

require-commands base64 gcloud require-envs
require-envs GCLOUD_KEYFILE GCLOUD_PROJECT

tmp_dir=${TMP_DIR:-"/tmp"}
registry_name=${REGISTRY_NAME:-"gcr.io"}

key_file="${tmp_dir}/gcloud-key-file.json"

echo "$GCLOUD_KEYFILE" | base64 -d > "${key_file}"
gcloud auth activate-service-account --key-file "${key_file}"
gcloud config set project $GCLOUD_PROJECT
gcloud auth configure-docker --quiet "${registry_name}"

exit 0
